import Suheib from "../Image/PFP_11.jpg";
import Non from "../Image/Non.jpg";

export const cardDescription = [
  {
    id: "0",
    Image: Suheib,
    Name: "Suheib Alabed",
    address: "Jordan,Irbid",
    Work: "Full Stack",
    Description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab commodi pariatur, accusamus dignissimos enim ratione.",
    facebook: "https://www.facebook.com/suheib.alabed/",
    instagram: "https://www.facebook.com/suheib.alabed/",
    twitter: "https://www.facebook.com/suheib.alabed/",
  },
  {
    id: "1",
    Image: Non,
    Name: "Mohammad Bdour",
    address: "Jordan,Irbid",
    Work: "Full Stack",
    Description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab commodi pariatur, accusamus dignissimos enim ratione.",
    facebook: "https://www.facebook.com/suheib.alabed/",
    instagram: "https://www.facebook.com/suheib.alabed/",
    twitter: "https://www.facebook.com/suheib.alabed/",
  },
  {
    id: "2",
    Image: Non,
    Name: "Monther Twaissi",
    address: "Jordan,Jarash",
    Work: "Full Stack",
    Description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab commodi pariatur, accusamus dignissimos enim ratione.",
    facebook: "https://www.facebook.com/suheib.alabed/",
    instagram: "https://www.facebook.com/suheib.alabed/",
    twitter: "https://www.facebook.com/suheib.alabed/",
  },

  {
    id: "3",
    Image: Non,
    Name: "Ahmad E'mar",
    address: "Jordan,Amman",
    Work: "Full Stack",
    Description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab commodi pariatur, accusamus dignissimos enim ratione.",
    facebook: "https://www.facebook.com/suheib.alabed/",
    instagram: "https://www.facebook.com/suheib.alabed/",
    twitter: "https://www.facebook.com/suheib.alabed/",
  },
  {
    id: "4",
    Image: Non,
    Name: "Osama Aburabi'e",
    address: "Jordan,Amman",
    Work: "Full Stack",
    Description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab commodi pariatur, accusamus dignissimos enim ratione.",
    facebook: "https://www.facebook.com/suheib.alabed/",
    instagram: "https://www.facebook.com/suheib.alabed/",
    twitter: "https://www.facebook.com/suheib.alabed/",
  },
  {
    id: "5",
    Image: Non,
    Name: "abdallah alhajeid",
    address: "Jordan,Amman",
    Work: "Full Stack",
    Description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab commodi pariatur, accusamus dignissimos enim ratione.",
    facebook: "https://www.facebook.com/suheib.alabed/",
    instagram: "https://www.facebook.com/suheib.alabed/",
    twitter: "https://www.facebook.com/suheib.alabed/",
  },
  {
    id: "6",
    Image: Non,
    Name: "Abdel rahman Abdaldeen",
    address: "Jordan,Amman",
    Work: "Full Stack",
    Description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab commodi pariatur, accusamus dignissimos enim ratione.",
    facebook: "https://www.facebook.com/suheib.alabed/",
    instagram: "https://www.facebook.com/suheib.alabed/",
    twitter: "https://www.facebook.com/suheib.alabed/",
  },
  {
    id: "7",
    Image: Non,
    Name: "Anas Aljawabrah",
    address: "Jordan,Amman",
    Work: "Full Stack",
    Description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab commodi pariatur, accusamus dignissimos enim ratione.",
    facebook: "https://www.facebook.com/suheib.alabed/",
    instagram: "https://www.facebook.com/suheib.alabed/",
    twitter: "https://www.facebook.com/suheib.alabed/",
  },
  {
    id: "8",
    Image: Non,
    Name: "Angham Bani-Younes",
    address: "Jordan,Amman",
    Work: "Full Stack",
    Description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab commodi pariatur, accusamus dignissimos enim ratione.",
    facebook: "https://www.facebook.com/suheib.alabed/",
    instagram: "https://www.facebook.com/suheib.alabed/",
    twitter: "https://www.facebook.com/suheib.alabed/",
  },
  {
    id: "9",
    Image: Non,
    Name: "Ashraf Al Jabari",
    address: "Jordan,Amman",
    Work: "Full Stack",
    Description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab commodi pariatur, accusamus dignissimos enim ratione.",
    facebook: "https://www.facebook.com/suheib.alabed/",
    instagram: "https://www.facebook.com/suheib.alabed/",
    twitter: "https://www.facebook.com/suheib.alabed/",
  },
  {
    id: "10",
    Image: Non,
    Name: "Ayah Imad",
    address: "Jordan,Amman",
    Work: "Full Stack",
    Description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab commodi pariatur, accusamus dignissimos enim ratione.",
    facebook: "https://www.facebook.com/suheib.alabed/",
    instagram: "https://www.facebook.com/suheib.alabed/",
    twitter: "https://www.facebook.com/suheib.alabed/",
  },
  {
    id: "11",
    Image: Non,
    Name: "Dana Toughoj",
    address: "Jordan,Amman",
    Work: "Full Stack",
    Description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab commodi pariatur, accusamus dignissimos enim ratione.",
    facebook: "https://www.facebook.com/suheib.alabed/",
    instagram: "https://www.facebook.com/suheib.alabed/",
    twitter: "https://www.facebook.com/suheib.alabed/",
  },
  {
    id: "12",
    Image: Non,
    Name: "Diaa Jamel",
    address: "Jordan,Amman",
    Work: "Full Stack",
    Description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab commodi pariatur, accusamus dignissimos enim ratione.",
    facebook: "https://www.facebook.com/suheib.alabed/",
    instagram: "https://www.facebook.com/suheib.alabed/",
    twitter: "https://www.facebook.com/suheib.alabed/",
  },
  {
    id: "13",
    Image: Non,
    Name: "Hala Al Hyasat",
    address: "Jordan,Amman",
    Work: "Full Stack",
    Description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab commodi pariatur, accusamus dignissimos enim ratione.",
    facebook: "https://www.facebook.com/suheib.alabed/",
    instagram: "https://www.facebook.com/suheib.alabed/",
    twitter: "https://www.facebook.com/suheib.alabed/",
  },
  {
    id: "14",
    Image: Non,
    Name: "Heba Bilbeisi",
    address: "Jordan,Amman",
    Work: "Full Stack",
    Description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab commodi pariatur, accusamus dignissimos enim ratione.",
    facebook: "https://www.facebook.com/suheib.alabed/",
    instagram: "https://www.facebook.com/suheib.alabed/",
    twitter: "https://www.facebook.com/suheib.alabed/",
  },
  {
    id: "15",
    Image: Non,
    Name: "Jenanmusallam",
    address: "Jordan,Amman",
    Work: "Full Stack",
    Description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab commodi pariatur, accusamus dignissimos enim ratione.",
    facebook: "https://www.facebook.com/suheib.alabed/",
    instagram: "https://www.facebook.com/suheib.alabed/",
    twitter: "https://www.facebook.com/suheib.alabed/",
  },
  {
    id: "16",
    Image: Non,
    Name: "leen awad",
    address: "Jordan,Amman",
    Work: "Full Stack",
    Description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab commodi pariatur, accusamus dignissimos enim ratione.",
    facebook: "https://www.facebook.com/suheib.alabed/",
    instagram: "https://www.facebook.com/suheib.alabed/",
    twitter: "https://www.facebook.com/suheib.alabed/",
  },
  {
    id: "17",
    Image: Non,
    Name: "lubna amjad",
    address: "Jordan,Amman",
    Work: "Full Stack",
    Description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab commodi pariatur, accusamus dignissimos enim ratione.",
    facebook: "https://www.facebook.com/suheib.alabed/",
    instagram: "https://www.facebook.com/suheib.alabed/",
    twitter: "https://www.facebook.com/suheib.alabed/",
  },
  {
    id: "18",
    Image: Non,
    Name: "Maysam Al-Turk",
    address: "Jordan,Amman",
    Work: "Full Stack",
    Description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab commodi pariatur, accusamus dignissimos enim ratione.",
    facebook: "https://www.facebook.com/suheib.alabed/",
    instagram: "https://www.facebook.com/suheib.alabed/",
    twitter: "https://www.facebook.com/suheib.alabed/",
  },
  {
    id: "19",
    Image: Non,
    Name: "Mohammed AL-Agi",
    address: "Jordan,Amman",
    Work: "Full Stack",
    Description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab commodi pariatur, accusamus dignissimos enim ratione.",
    facebook: "https://www.facebook.com/suheib.alabed/",
    instagram: "https://www.facebook.com/suheib.alabed/",
    twitter: "https://www.facebook.com/suheib.alabed/",
  },
  {
    id: "20",
    Image: Non,
    Name: "Mohammed Aljasem",
    address: "Jordan,Amman",
    Work: "Full Stack",
    Description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab commodi pariatur, accusamus dignissimos enim ratione.",
    facebook: "https://www.facebook.com/suheib.alabed/",
    instagram: "https://www.facebook.com/suheib.alabed/",
    twitter: "https://www.facebook.com/suheib.alabed/",
  },
  {
    id: "21",
    Image: Non,
    Name: "Razan Zuaiter",
    address: "Jordan,Amman",
    Work: "Full Stack",
    Description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab commodi pariatur, accusamus dignissimos enim ratione.",
    facebook: "https://www.facebook.com/suheib.alabed/",
    instagram: "https://www.facebook.com/suheib.alabed/",
    twitter: "https://www.facebook.com/suheib.alabed/",
  },
  {
    id: "22",
    Image: Non,
    Name: "Saja dahamsheh",
    address: "Jordan,Amman",
    Work: "Full Stack",
    Description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab commodi pariatur, accusamus dignissimos enim ratione.",
    facebook: "https://www.facebook.com/suheib.alabed/",
    instagram: "https://www.facebook.com/suheib.alabed/",
    twitter: "https://www.facebook.com/suheib.alabed/",
  },
  {
    id: "23",
    Image: Non,
    Name: "Sarah Eswed",
    address: "Jordan,Amman",
    Work: "Full Stack",
    Description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab commodi pariatur, accusamus dignissimos enim ratione.",
    facebook: "https://www.facebook.com/suheib.alabed/",
    instagram: "https://www.facebook.com/suheib.alabed/",
    twitter: "https://www.facebook.com/suheib.alabed/",
  },
  {
    id: "24",
    Image: Non,
    Name: "Taima Al-fokaha",
    address: "Jordan,Amman",
    Work: "Full Stack",
    Description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab commodi pariatur, accusamus dignissimos enim ratione.",
    facebook: "https://www.facebook.com/suheib.alabed/",
    instagram: "https://www.facebook.com/suheib.alabed/",
    twitter: "https://www.facebook.com/suheib.alabed/",
  },
  {
    id: "25",
    Image: Non,
    Name: "Waed Dawaghreh",
    address: "Jordan,Amman",
    Work: "Full Stack",
    Description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab commodi pariatur, accusamus dignissimos enim ratione.",
    facebook: "https://www.facebook.com/suheib.alabed/",
    instagram: "https://www.facebook.com/suheib.alabed/",
    twitter: "https://www.facebook.com/suheib.alabed/",
  },
  {
    id: "26",
    Image: Non,
    Name: "Mohammad Alzoubi",
    address: "Jordan,Amman",
    Work: "Full Stack",
    Description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab commodi pariatur, accusamus dignissimos enim ratione.",
    facebook: "https://www.facebook.com/suheib.alabed/",
    instagram: "https://www.facebook.com/suheib.alabed/",
    twitter: "https://www.facebook.com/suheib.alabed/",
  },
  {
    id: "27",
    Image: Non,
    Name: "Mohammad Al-Shwaiki",
    address: "Jordan,Amman",
    Work: "Full Stack",
    Description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab commodi pariatur, accusamus dignissimos enim ratione.",
    facebook: "https://www.facebook.com/suheib.alabed/",
    instagram: "https://www.facebook.com/suheib.alabed/",
    twitter: "https://www.facebook.com/suheib.alabed/",
  },
  {
    id: "28",
    Image: Non,
    Name: "Khadeejah Hamdan",
    address: "Jordan,Amman",
    Work: "Full Stack",
    Description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab commodi pariatur, accusamus dignissimos enim ratione.",
    facebook: "https://www.facebook.com/suheib.alabed/",
    instagram: "https://www.facebook.com/suheib.alabed/",
    twitter: "https://www.facebook.com/suheib.alabed/",
  },
  {
    id: "29",
    Image: Non,
    Name: "Amal Al-Dajah",
    address: "Jordan,Amman",
    Work: "Full Stack",
    Description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab commodi pariatur, accusamus dignissimos enim ratione.",
    facebook: "https://www.facebook.com/suheib.alabed/",
    instagram: "https://www.facebook.com/suheib.alabed/",
    twitter: "https://www.facebook.com/suheib.alabed/",
  },
];
